name: "AUY1105 - PipelineCI-Grupo4"

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  iac_pipeline:
    name: "Pipeline de Calidad e Infraestructura"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.50.0

      - name: TFLint Init
        run: tflint --init

      - name: TFLint Run
        run: tflint -f compact

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: pip3 install checkov

      - name: Checkov Static Analysis
        run: |
          checkov -d . \
            --framework terraform \
            --download-external-modules true \
            --skip-check CKV_AWS_135,CKV_AWS_260,CKV2_AWS_5,CKV_TF_1 \
            --quiet

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (Generar JSON para OPA)
        env:
          TF_VAR_mi_ip_acceso: ${{ secrets.MI_IP_ACCESO }}
        run: |
          terraform plan -out=tfplan
          terraform show -json tfplan > tfplan.json

      - name: Setup OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/v0.61.0/opa_linux_amd64_static
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Evaluar Política de Seguridad y Región
        run: opa eval -i tfplan.json -d policies/region_check.rego "data.terraform.authz.allow" --fail

      - name: Evaluar Política de Nomenclatura e Instancia
        run: opa eval -i tfplan.json -d policies/name_check.rego "data.terraform.authz.allow" --fail